package complaintProcess;
// Generated Aug 31, 2019 12:09:55 AM by Hibernate Tools 4.3.1



/**
 * CommitteeStaff generated by hbm2java
 */
public class CommitteeStaff  implements java.io.Serializable {


     private Integer idcommitteeStaff;
     private Committee committee;
     private Staff staff;
     private String status;
     private String comment;

    public CommitteeStaff() {
    }

	
    public CommitteeStaff(Committee committee, Staff staff, String status) {
        this.committee = committee;
        this.staff = staff;
        this.status = status;
    }
    public CommitteeStaff(Committee committee, Staff staff, String status, String comment) {
       this.committee = committee;
       this.staff = staff;
       this.status = status;
       this.comment = comment;
    }
   
    public Integer getIdcommitteeStaff() {
        return this.idcommitteeStaff;
    }
    
    public void setIdcommitteeStaff(Integer idcommitteeStaff) {
        this.idcommitteeStaff = idcommitteeStaff;
    }
    public Committee getCommittee() {
        return this.committee;
    }
    
    public void setCommittee(Committee committee) {
        this.committee = committee;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


