package complaintProcess;
// Generated Aug 31, 2019 12:09:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Committee generated by hbm2java
 */
public class Committee  implements java.io.Serializable {


     private Integer idCommittee;
     private String name;
     private Date createdUp;
     private Date updatedUp;
     private Set<CommitteeStaff> committeeStaffs = new HashSet<CommitteeStaff>(0);

    public Committee() {
    }

	
    public Committee(String name, Date createdUp) {
        this.name = name;
        this.createdUp = createdUp;
    }
    public Committee(String name, Date createdUp, Date updatedUp, Set<CommitteeStaff> committeeStaffs) {
       this.name = name;
       this.createdUp = createdUp;
       this.updatedUp = updatedUp;
       this.committeeStaffs = committeeStaffs;
    }
   
    public Integer getIdCommittee() {
        return this.idCommittee;
    }
    
    public void setIdCommittee(Integer idCommittee) {
        this.idCommittee = idCommittee;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreatedUp() {
        return this.createdUp;
    }
    
    public void setCreatedUp(Date createdUp) {
        this.createdUp = createdUp;
    }
    public Date getUpdatedUp() {
        return this.updatedUp;
    }
    
    public void setUpdatedUp(Date updatedUp) {
        this.updatedUp = updatedUp;
    }
    public Set<CommitteeStaff> getCommitteeStaffs() {
        return this.committeeStaffs;
    }
    
    public void setCommitteeStaffs(Set<CommitteeStaff> committeeStaffs) {
        this.committeeStaffs = committeeStaffs;
    }




}


