package complaintProcess;
// Generated Aug 31, 2019 12:09:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private Integer iddepartment;
     private String name;
     private Date createdUp;
     private Date updatedUp;
     private Set<Staff> staffs = new HashSet<Staff>(0);

    public Department() {
    }

	
    public Department(String name, Date createdUp) {
        this.name = name;
        this.createdUp = createdUp;
    }
    public Department(String name, Date createdUp, Date updatedUp, Set<Staff> staffs) {
       this.name = name;
       this.createdUp = createdUp;
       this.updatedUp = updatedUp;
       this.staffs = staffs;
    }
   
    public Integer getIddepartment() {
        return this.iddepartment;
    }
    
    public void setIddepartment(Integer iddepartment) {
        this.iddepartment = iddepartment;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreatedUp() {
        return this.createdUp;
    }
    
    public void setCreatedUp(Date createdUp) {
        this.createdUp = createdUp;
    }
    public Date getUpdatedUp() {
        return this.updatedUp;
    }
    
    public void setUpdatedUp(Date updatedUp) {
        this.updatedUp = updatedUp;
    }
    public Set<Staff> getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set<Staff> staffs) {
        this.staffs = staffs;
    }




}


