package complaintProcess;
// Generated Aug 31, 2019 12:09:55 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Process generated by hbm2java
 */
public class Process  implements java.io.Serializable {


     private Integer idprocess;
     private Complaint complaint;
     private String status;
     private byte mailSent;
     private byte controlPointContacted;
     private byte isThereEvidence;
     private byte notificationToSuperior;
     private byte verbalNotification;
     private byte writtenNotification;
     private byte recurrence;
     private byte interruptContact;
     private String recurrenceReport;
     private String committeeEvaluation;
     private Date createdUp;
     private Date updatedUp;

    public Process() {
    }

	
    public Process(String status, byte mailSent, byte controlPointContacted, byte isThereEvidence, byte notificationToSuperior, byte verbalNotification, byte writtenNotification, byte recurrence, byte interruptContact, Date createdUp) {
        this.status = status;
        this.mailSent = mailSent;
        this.controlPointContacted = controlPointContacted;
        this.isThereEvidence = isThereEvidence;
        this.notificationToSuperior = notificationToSuperior;
        this.verbalNotification = verbalNotification;
        this.writtenNotification = writtenNotification;
        this.recurrence = recurrence;
        this.interruptContact = interruptContact;
        this.createdUp = createdUp;
    }
    public Process(Complaint complaint, String status, byte mailSent, byte controlPointContacted, byte isThereEvidence, byte notificationToSuperior, byte verbalNotification, byte writtenNotification, byte recurrence, byte interruptContact, String recurrenceReport, String committeeEvaluation, Date createdUp, Date updatedUp) {
       this.complaint = complaint;
       this.status = status;
       this.mailSent = mailSent;
       this.controlPointContacted = controlPointContacted;
       this.isThereEvidence = isThereEvidence;
       this.notificationToSuperior = notificationToSuperior;
       this.verbalNotification = verbalNotification;
       this.writtenNotification = writtenNotification;
       this.recurrence = recurrence;
       this.interruptContact = interruptContact;
       this.recurrenceReport = recurrenceReport;
       this.committeeEvaluation = committeeEvaluation;
       this.createdUp = createdUp;
       this.updatedUp = updatedUp;
    }
   
    public Integer getIdprocess() {
        return this.idprocess;
    }
    
    public void setIdprocess(Integer idprocess) {
        this.idprocess = idprocess;
    }
    public Complaint getComplaint() {
        return this.complaint;
    }
    
    public void setComplaint(Complaint complaint) {
        this.complaint = complaint;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public byte getMailSent() {
        return this.mailSent;
    }
    
    public void setMailSent(byte mailSent) {
        this.mailSent = mailSent;
    }
    public byte getControlPointContacted() {
        return this.controlPointContacted;
    }
    
    public void setControlPointContacted(byte controlPointContacted) {
        this.controlPointContacted = controlPointContacted;
    }
    public byte getIsThereEvidence() {
        return this.isThereEvidence;
    }
    
    public void setIsThereEvidence(byte isThereEvidence) {
        this.isThereEvidence = isThereEvidence;
    }
    public byte getNotificationToSuperior() {
        return this.notificationToSuperior;
    }
    
    public void setNotificationToSuperior(byte notificationToSuperior) {
        this.notificationToSuperior = notificationToSuperior;
    }
    public byte getVerbalNotification() {
        return this.verbalNotification;
    }
    
    public void setVerbalNotification(byte verbalNotification) {
        this.verbalNotification = verbalNotification;
    }
    public byte getWrittenNotification() {
        return this.writtenNotification;
    }
    
    public void setWrittenNotification(byte writtenNotification) {
        this.writtenNotification = writtenNotification;
    }
    public byte getRecurrence() {
        return this.recurrence;
    }
    
    public void setRecurrence(byte recurrence) {
        this.recurrence = recurrence;
    }
    public byte getInterruptContact() {
        return this.interruptContact;
    }
    
    public void setInterruptContact(byte interruptContact) {
        this.interruptContact = interruptContact;
    }
    public String getRecurrenceReport() {
        return this.recurrenceReport;
    }
    
    public void setRecurrenceReport(String recurrenceReport) {
        this.recurrenceReport = recurrenceReport;
    }
    public String getCommitteeEvaluation() {
        return this.committeeEvaluation;
    }
    
    public void setCommitteeEvaluation(String committeeEvaluation) {
        this.committeeEvaluation = committeeEvaluation;
    }
    public Date getCreatedUp() {
        return this.createdUp;
    }
    
    public void setCreatedUp(Date createdUp) {
        this.createdUp = createdUp;
    }
    public Date getUpdatedUp() {
        return this.updatedUp;
    }
    
    public void setUpdatedUp(Date updatedUp) {
        this.updatedUp = updatedUp;
    }




}


