package complaintProcess;
// Generated Aug 31, 2019 12:09:55 AM by Hibernate Tools 4.3.1



/**
 * RolePrivilege generated by hbm2java
 */
public class RolePrivilege  implements java.io.Serializable {


     private Integer idrolePrivilege;
     private Privilege privilege;
     private Role role;
     private byte status;
     private String comment;

    public RolePrivilege() {
    }

	
    public RolePrivilege(Privilege privilege, Role role, byte status) {
        this.privilege = privilege;
        this.role = role;
        this.status = status;
    }
    public RolePrivilege(Privilege privilege, Role role, byte status, String comment) {
       this.privilege = privilege;
       this.role = role;
       this.status = status;
       this.comment = comment;
    }
   
    public Integer getIdrolePrivilege() {
        return this.idrolePrivilege;
    }
    
    public void setIdrolePrivilege(Integer idrolePrivilege) {
        this.idrolePrivilege = idrolePrivilege;
    }
    public Privilege getPrivilege() {
        return this.privilege;
    }
    
    public void setPrivilege(Privilege privilege) {
        this.privilege = privilege;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


