package complaintProcess;
// Generated Aug 31, 2019 12:09:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer idrole;
     private String roleName;
     private Date createdUp;
     private Date updatedUp;
     private Set<RolePrivilege> rolePrivileges = new HashSet<RolePrivilege>(0);
     private Set<Staff> staffs = new HashSet<Staff>(0);
     private Set<UserRole> userRoles = new HashSet<UserRole>(0);

    public Role() {
    }

	
    public Role(String roleName, Date createdUp) {
        this.roleName = roleName;
        this.createdUp = createdUp;
    }
    public Role(String roleName, Date createdUp, Date updatedUp, Set<RolePrivilege> rolePrivileges, Set<Staff> staffs, Set<UserRole> userRoles) {
       this.roleName = roleName;
       this.createdUp = createdUp;
       this.updatedUp = updatedUp;
       this.rolePrivileges = rolePrivileges;
       this.staffs = staffs;
       this.userRoles = userRoles;
    }
   
    public Integer getIdrole() {
        return this.idrole;
    }
    
    public void setIdrole(Integer idrole) {
        this.idrole = idrole;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public Date getCreatedUp() {
        return this.createdUp;
    }
    
    public void setCreatedUp(Date createdUp) {
        this.createdUp = createdUp;
    }
    public Date getUpdatedUp() {
        return this.updatedUp;
    }
    
    public void setUpdatedUp(Date updatedUp) {
        this.updatedUp = updatedUp;
    }
    public Set<RolePrivilege> getRolePrivileges() {
        return this.rolePrivileges;
    }
    
    public void setRolePrivileges(Set<RolePrivilege> rolePrivileges) {
        this.rolePrivileges = rolePrivileges;
    }
    public Set<Staff> getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set<Staff> staffs) {
        this.staffs = staffs;
    }
    public Set<UserRole> getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(Set<UserRole> userRoles) {
        this.userRoles = userRoles;
    }




}


