package complaintProcess;
// Generated Aug 31, 2019 12:09:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private Integer idstaff;
     private Department department;
     private Role role;
     private User user;
     private String name;
     private String lastname;
     private String email;
     private String status;
     private Date createdUp;
     private Date updatedUp;
     private Set<Complaint> complaints = new HashSet<Complaint>(0);
     private Set<CommitteeStaff> committeeStaffs = new HashSet<CommitteeStaff>(0);

    public Staff() {
    }

	
    public Staff(Department department, Role role, User user, String name, String lastname, String email, String status, Date createdUp) {
        this.department = department;
        this.role = role;
        this.user = user;
        this.name = name;
        this.lastname = lastname;
        this.email = email;
        this.status = status;
        this.createdUp = createdUp;
    }
    public Staff(Department department, Role role, User user, String name, String lastname, String email, String status, Date createdUp, Date updatedUp, Set<Complaint> complaints, Set<CommitteeStaff> committeeStaffs) {
       this.department = department;
       this.role = role;
       this.user = user;
       this.name = name;
       this.lastname = lastname;
       this.email = email;
       this.status = status;
       this.createdUp = createdUp;
       this.updatedUp = updatedUp;
       this.complaints = complaints;
       this.committeeStaffs = committeeStaffs;
    }
   
    public Integer getIdstaff() {
        return this.idstaff;
    }
    
    public void setIdstaff(Integer idstaff) {
        this.idstaff = idstaff;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getCreatedUp() {
        return this.createdUp;
    }
    
    public void setCreatedUp(Date createdUp) {
        this.createdUp = createdUp;
    }
    public Date getUpdatedUp() {
        return this.updatedUp;
    }
    
    public void setUpdatedUp(Date updatedUp) {
        this.updatedUp = updatedUp;
    }
    public Set<Complaint> getComplaints() {
        return this.complaints;
    }
    
    public void setComplaints(Set<Complaint> complaints) {
        this.complaints = complaints;
    }
    public Set<CommitteeStaff> getCommitteeStaffs() {
        return this.committeeStaffs;
    }
    
    public void setCommitteeStaffs(Set<CommitteeStaff> committeeStaffs) {
        this.committeeStaffs = committeeStaffs;
    }




}


