package complaintProcess;
// Generated Aug 31, 2019 12:09:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TypeUser generated by hbm2java
 */
public class TypeUser  implements java.io.Serializable {


     private Integer idtypeUser;
     private String typeUserName;
     private Date createdUp;
     private Date updatedUp;
     private Set<User> users = new HashSet<User>(0);

    public TypeUser() {
    }

	
    public TypeUser(String typeUserName, Date createdUp) {
        this.typeUserName = typeUserName;
        this.createdUp = createdUp;
    }
    public TypeUser(String typeUserName, Date createdUp, Date updatedUp, Set<User> users) {
       this.typeUserName = typeUserName;
       this.createdUp = createdUp;
       this.updatedUp = updatedUp;
       this.users = users;
    }
   
    public Integer getIdtypeUser() {
        return this.idtypeUser;
    }
    
    public void setIdtypeUser(Integer idtypeUser) {
        this.idtypeUser = idtypeUser;
    }
    public String getTypeUserName() {
        return this.typeUserName;
    }
    
    public void setTypeUserName(String typeUserName) {
        this.typeUserName = typeUserName;
    }
    public Date getCreatedUp() {
        return this.createdUp;
    }
    
    public void setCreatedUp(Date createdUp) {
        this.createdUp = createdUp;
    }
    public Date getUpdatedUp() {
        return this.updatedUp;
    }
    
    public void setUpdatedUp(Date updatedUp) {
        this.updatedUp = updatedUp;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


