package complaintProcess;
// Generated Aug 31, 2019 12:09:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TypeAbuse generated by hbm2java
 */
public class TypeAbuse  implements java.io.Serializable {


     private Integer idtypeAbuse;
     private String name;
     private Date createdUp;
     private Date updatedUp;
     private Set<Complaint> complaints = new HashSet<Complaint>(0);

    public TypeAbuse() {
    }

	
    public TypeAbuse(String name, Date createdUp) {
        this.name = name;
        this.createdUp = createdUp;
    }
    public TypeAbuse(String name, Date createdUp, Date updatedUp, Set<Complaint> complaints) {
       this.name = name;
       this.createdUp = createdUp;
       this.updatedUp = updatedUp;
       this.complaints = complaints;
    }
   
    public Integer getIdtypeAbuse() {
        return this.idtypeAbuse;
    }
    
    public void setIdtypeAbuse(Integer idtypeAbuse) {
        this.idtypeAbuse = idtypeAbuse;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreatedUp() {
        return this.createdUp;
    }
    
    public void setCreatedUp(Date createdUp) {
        this.createdUp = createdUp;
    }
    public Date getUpdatedUp() {
        return this.updatedUp;
    }
    
    public void setUpdatedUp(Date updatedUp) {
        this.updatedUp = updatedUp;
    }
    public Set<Complaint> getComplaints() {
        return this.complaints;
    }
    
    public void setComplaints(Set<Complaint> complaints) {
        this.complaints = complaints;
    }




}


