package complaintProcess;
// Generated Aug 31, 2019 12:09:55 AM by Hibernate Tools 4.3.1



/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private Integer iduserRole;
     private Role role;
     private User user;
     private byte status;
     private String comment;

    public UserRole() {
    }

	
    public UserRole(Role role, User user, byte status) {
        this.role = role;
        this.user = user;
        this.status = status;
    }
    public UserRole(Role role, User user, byte status, String comment) {
       this.role = role;
       this.user = user;
       this.status = status;
       this.comment = comment;
    }
   
    public Integer getIduserRole() {
        return this.iduserRole;
    }
    
    public void setIduserRole(Integer iduserRole) {
        this.iduserRole = iduserRole;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


